Device statistics - backend
IAmAnatolyBelanov/InfotecsTestPeriodTask pull request #1
Opened 2023-06-28 12:08 UTC by IAmAnatolyBelanov

2023-06-28 15:55 UTC, adcy requested changes

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +public class DeviceController : ControllerBase
Все публичные члены должны иметь комментарии [Documentation comments](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/). 
Необходимо во все .csprоj файлы добавить `<GenerateDocumentationFile>true</GenerateDocumentationFile>`, тогда IDE подсветит все места, где требуется документация.

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Monitoring.sln
infotecs.ruleset и .editorconfig нужно также закомитить, тогда у всех членов команды будут одинаковые правила

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +public class DeviceBizRule : IDeviceBizRule, IDisposable, IAsyncDisposable
1. Я бы предпочел видеть вместо термина BizRule, более общепринятый термин Service.
2. Если это Rule, т.е. одно правило, то почему тут несколько методов? И что тогда вообще Rule? Какие критерии разделения на правила?

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/BaseResponse.cs
> +public static class BaseResponseExtensions
Предлагаю вынести.  В команде придерживаемся правила 1 файл = 1 класс.

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Monitoring.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Monitoring.Bll", "Source\Monitoring.Bll\Monitoring.Bll.csproj", "{098EA75A-28CB-4158-992B-C6C6D1C932CC}"
`Bll` явно не общепринятый термин, лучше полное наименование использовать.

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/LoginController.cs
> +public class LoginController : ControllerBase
Я так понимаю, что это получение статистики от устройства? Но в задании ничего не было про то, что это статистика "входа". Может быть устройства - это какие-нибудь датчики, где вообще не существует сценария "входа".

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +            .Where(x => x.DeviceId == deviceId && x.DateTime >= dateFrom && x.DateTime < dateTo)
В ТЗ ничего нет про фильтрацию статистики по времени.

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/LoginBizRules/LoginBizRule.cs
> +        await _context.SaveChangesAsync(cancellationToken);
Если нужно будет взывать на один запрос от клиента несколько "правил", по какой логике будут комититься изменения?

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
Почему используется VlaueTask, а не обычный Task?

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +        if (pagination.PageIndex < 0)
А если паджинация никогда не понадобится, а мы на неё время потратили? :)

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +        catch (ClientException ex)
А в каком случае возникает ClientException?

2023-06-28 15:55 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask DisposeAsync() => await _context.DisposeAsync();
А если в другом классе в рамках этого же запроса кто-то еще использует _context, а тут Dispose на нем вызывается?

2023-06-28 15:57 UTC, adcy requested changes
Не увидел логирования "получения статистики от устройств, добавление или обновление статистики устройства, запросов от клиента"

2023-06-28 16:18 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Monitoring.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Monitoring.Bll", "Source\Monitoring.Bll\Monitoring.Bll.csproj", "{098EA75A-28CB-4158-992B-C6C6D1C932CC}"
BusinessLogicLayer. Был уверен, что такой же общепринятый, как dal. Ну ок - переименую

2023-06-28 16:26 UTC, IAmAnatolyBelanov commented
![image](https://github.com/IAmAnatolyBelanov/InfotecsTestPeriodTask/assets/98072721/dfc50d0d-6816-4369-b75b-31a6c6b89ea5)

Логгирование идёт автоматом. Конструкция  `new LoggerConfiguration().Enrich.FromLogContext()` добавляет инфу о запросе в каждый лог

2023-06-28 16:29 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +        if (pagination.PageIndex < 0)
Всё может быть. Но вроде как обоснованные отхождения от тз допустимы. И тут я этим предпочту воспользоваться. Не очень люблю давать юзеру возможность стянуть всю бд без ограничений - страшно как-то. Большая нагрузка и на наши серваки, и на канал связи, и на клиент

2023-06-28 16:30 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +        catch (ClientException ex)
Когда клиент может исправить ситуацию. Как пример - когда при пагинации запросил -1 страницу. С такой ошибкой клиент сможет совладать, и надо бы ему помочь - сказать, что именно не так

2023-06-28 16:38 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
Ожидаю, что этот метод будет вызван лишь синхронно. Могу быть не прав - тогда код придётся слегка переписать - заюзать обычный Task. На текущей же реализации имхо ValueTask должен работать лучше (но бенчи не гонял - это скорее мнение на основе статей из интернетов)

2023-06-28 16:44 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Bll/LoginBizRules/LoginBizRule.cs
> +        await _context.SaveChangesAsync(cancellationToken);
Сейчас - на каждый вызов метода в "правиле" будет свой коммит. Возможно, во время дальнейшего развития продукта понадобится пересмотреть подход

2023-06-28 20:19 UTC, SergerGood requested changes

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/Paginations/Pagination.cs
> +    public int PageIndex { get; set; }
Рекорды это все таки про неизменяемык данные. А у тебя сеттер публичный. В чем тогда смысл рекорда здесь?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/Paginations/Pagination.cs
> +    /// Индекс страницы. Отсчёт начинается с 0.
Отсчёт начинается с 0. Больше похоже на ремарка.

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/Exceptions/ClientException.cs
> +    public ClientException() : base() { }
Не слишком название привязанность к потребителю? А если ошибки будут не только клиентские? Например другой сервис

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/Exceptions/ClientException.cs
> +    public ClientException(string? message) : base(message) { }
Мне кажется для такого объекта как ошибка значение ошибки не должно быть налбл

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/DateTimeProviders/IClock.cs
> +    DateTimeOffset Now { get; }
А в чем смысл оба значения иметь? У нас планируется работа с обоими форматами?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/DateTimeProviders/Clock.cs
> +    public DateTimeOffset UtcNow => DateTimeOffset.UtcNow;
Пока не понял зачем была введена эта абстракция

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/MonitoringContext.cs
> +}
Logins? А такое понятие в задании было разве?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/MonitoringContext.cs
> +        optionsBuilder.UseInMemoryDatabase("AppDb");
Ef нам канечно даёт возможность работать в инмемори, но все же очень многое тащит за собой и задаёт уже правила игры. По сути дела по заданию требовалось хранить в памяти а для этого можно хоть в коллекциях хранить. Не избыточно?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Models/LoginInfo.cs
> +    public Guid Id { get; set; }
Вот поле ID в обеих моделях появились изза EF?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Models/LoginInfo.cs
> +    public DateTimeOffset DateTime { get; set; }
Не помню модель по заданию. А тут datetime что было?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Bll/Monitoring.Bll.csproj
> +    <WarningLevel>4</WarningLevel>
Не лишнее? Не помню для чего

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Bll/Monitoring.Bll.csproj
> +    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
Вот в релизе должно быть тру

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +public class DeviceBizRule : IDeviceBizRule, IDisposable, IAsyncDisposable
Соглашусь

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
Во всех этих статьях пишут что vakuetask нужно использовать только очень хорошо подумав для каждой конкретной ситуации. А у нас вроде только все начинается и наверняка изменится

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
Кстати вся тут асинхронщина не понятна для чего, потому что текущая реализация в памяти

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/LoggerRegister.cs
> +    public static void RegisterLogger(WebApplicationBuilder builder)
А почему не метод расширение?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +#if DEBUG
В контексте аспнет лучше работать с переменной окружения

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +            await context.Response.WriteAsync(JsonSerializer.Serialize(fail));
Метод какой-то большой сложно в мобиле читая понять что происходит

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +        if (pagination.PageIndex < 0)
Не много ли логике в контроллере?

2023-06-28 20:19 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    [HttpPost]
Для методов апи лучше явно прописывать пути, так понятно имена получаются ближе к классическом именованию апи и менее подвержены поломка при рефакторинге переименований

2023-06-29 05:11 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
> На текущей же реализации имхо ValueTask должен работать лучше

Сейчас внутри метода простой Task (возвращается из ToListAsync), из которого затем создаётся ValueTask для возврата из текущего метода. Т.е. как минимум ValueTask тут ничего не даёт.

2023-06-29 05:26 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +        catch (ClientException ex)
Тогда не должно быть что-то вроде InvalidRequestException? В моем понимании "исключение клиента", это когда некий "клиент" не может обработать данные, которые ему передали. А тут ведь сервер не может обработать.

2023-06-29 05:28 UTC, adcy commented on Backend/Monitoring/Monitoring.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Monitoring.Bll", "Source\Monitoring.Bll\Monitoring.Bll.csproj", "{098EA75A-28CB-4158-992B-C6C6D1C932CC}"
Ну вот где-то я встречал просто BL, например. А в последнее время чаще в комньюнити используется Domain.

2023-06-29 06:42 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +        catch (ClientException ex)
Можно и так, да. Таких исключений (аля InvalidRequestException) можно придумать довольно много, и они будут весьма специфичны. Как пример (высосанный из пальца, но тут и стоит цель максимальное разнообразие придумать), множество клиентов, которые пытаются отредачить один файл на сервере - мы естественно поймаем исключение от операционки, но клиенту нужно сказать, чтобы он повторил запрос через условных 30 секунд. Это уже не звучит как InvalidRequestException, но и вместе с тем инфа для клиента полезная.

Я привык к ClientException и наследникам ClientException для конкретных случаев. Для InvalidRequestException можно как раз отнаследоваться от ClientException, а в мидлваре оставить обработку только родительского ClientException. Пока не уверен, что нужные действия, но да - так можно

2023-06-29 06:45 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +#if DEBUG
Хм... Мидлварь для обработки исключений. Могу конечно разбить catch'и на отдельные методы, которые ещё и будут крайне похожи друг на друга... Но имхо тут это читаемость не повысит

2023-06-29 06:52 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
Можно вернуть саму таску, согласен. Не оборачивать в ещё одну таску/valueTask. `var result = _context...ToListAsync(); return result;` Но у такого подхода есть одно слабое место, ради которого я предпочитаю жертвовать производительностью. В случае exception'ов стек трейс будет указывать только на внутренности EF и на тот метод, который всё же за'await'ит таску. Искать потом корни сложнее.

Если в команде принято возвращать оригинальную таску и/или не играться с ValueTask - ок, переделаю. Этот момент мне не принципиален. Хотя предпочитаю всё же эвэйтить таски в своих методах

2023-06-29 06:55 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Models/LoginInfo.cs
> +    public Guid Id { get; set; }
Нет, потому что я предпочитаю иметь у сущностей айдишники. Бывают ситуации, когда они не нужны, но тут имхо простая ничем не примечательная модель - ей айдишник к лицу

2023-06-29 07:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/MonitoringContext.cs
> +        optionsBuilder.UseInMemoryDatabase("AppDb");
Можно хоть в коллекциях - да. Но всё же ни одно крупное приложение за мой опыт не обходилось без использования постоянного хранилища. И мой опыт подсказывает, что рано или поздно всё же понадобится перейти на что-то не inmemory. А так ef позволит переход осуществить максимально безболезненно.

На текущий момент да - избыточно. Можно более простыми коллекциями обойтись. Аля ConcurrentBag/ConcurrentQueue/ConcurrentDictionary. Но это тоже накладывает некоторые ограничения. Та же самая потокобезопасность. А раз выбирать приходится не просто из List vs EF, а всё же из (коллекции + потокобзопасность + самописный класс-контекст) vs EF, то я выбираю EF

2023-06-29 07:11 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Shared/DateTimeProviders/Clock.cs
> +    public DateTimeOffset UtcNow => DateTimeOffset.UtcNow;
На каком-то этапе жизненного цикла продукта возникает потребность обкладывать всё тестами. Для тестов DateTime.Now и его собратья - приговор (равно как и статичные методы/классы) (вообще, слышал, что какие-то библиотеки могут как-то замокать статику, но ни разу не щупал). Использование же абстракции позволяет прокинуть ту реализацию, что будет удобна для тестирования.

Тут снова можно спросить, не избыточно ли на текущий момент. Но всё же прокинуть сейчас такую абстракцию - дело пары минут. Поддерживать IClock не стоит вообще ничего (вернее, его использование во время разработки тратит столько же сил и времени, как и использование DateTimeOffset.UtcNow). А вот если такая штука с самого начала не прокинута, то поменять потом все места стоит довольно много сил и времени

2023-06-29 07:14 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Shared/Exceptions/ClientException.cs
> +    public ClientException() : base() { }
Для обработки ошибок с другого сервиса потребуется другой exception вводить. Моя задумка ClientException в том, что он содержит информацию, которую можно и нужно показать клиенту. А будет этот клиент человеком, или другим сервисом - не касается того кода, что выкидывает это исключение

2023-06-29 07:25 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +        if (pagination.PageIndex < 0)
Т.к. пока посыл не усложнять - удалю. А вообще, хотел переписать на FluentValidator, но он всё же требует больше  пары минут на реализацию и прокиывание - пока не стал

2023-06-29 19:22 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +            await context.Response.WriteAsync(JsonSerializer.Serialize(fail));
Хм... Мидлварь для обработки исключений. Могу конечно разбить catch'и на отдельные методы, которые ещё и будут крайне похожи друг на друга... Но имхо тут это читаемость не повысит

2023-06-29 19:24 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +#if DEBUG
Environment.GetEnvironmentVariable ? Или что-то типа чтения из конфига?

2023-06-29 19:41 UTC, SergerGood requested changes

2023-06-29 19:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +        if (pagination.PageIndex < 0)
Я про то что контроллеры обычно "тупые". Тут нет явной логики со статусами ответа. Как минимум такую логику хотя бы вынести куда-то, не обязательно переписывать.

2023-06-29 19:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +#if DEBUG
Я тут про if debug и что лучше работать с ASPNETCORE_ENVIRONMENT. Но видимо ты про следующий комментарий с большим методом. А почему не повысит? Для начала правильно названные методы позволят понимать что мы делаем. А потом имея вызовы методов на каждый кэтч мы увидим что в итоге происходит в коде, а не n строк кода

2023-06-29 19:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Models/LoginInfo.cs
> +    public Guid Id { get; set; }
Я к тому что он появился из-за привязки к ef. Ну ок

2023-06-29 19:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/MonitoringContext.cs
> +        optionsBuilder.UseInMemoryDatabase("AppDb");
Рассуждаешь правильно. Но заложить на все и сразу не получится. И в нашем положении что не говори в коллекции было бы сделать быстрее. Ок. Я не топлю за переделку, просто хотелось понять зачем. Посмотрим попмжет это дальше или нет

2023-06-29 19:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/DateTimeProviders/Clock.cs
> +    public DateTimeOffset UtcNow => DateTimeOffset.UtcNow;
Хорошо, понял. Но все таки есть мнение не вводить абстракции пока в этом нет необходимости

2023-06-29 19:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Shared/Exceptions/ClientException.cs
> +    public ClientException() : base() { }
Не много не уловил, кажется расхождение. Вроде говоришь что для обработки с другого сервиса придётся вводить другой тип ошибок... А приходишь к выводу что не важно. Твой метод рано или поздно сможет вызывать другой сервис. Но я наверное к тому что смысл ошибки не в том для кого она а в том из-за чего она или почему.

2023-06-29 19:55 UTC, SergerGood requested changes

2023-06-29 19:55 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +#if DEBUG
Попробуй заинжектить IWebHostEnvironment. Хотя такие вещи логичнее делать на уровне регистрации мидлвар

2023-06-30 06:04 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +        catch (ClientException ex)
Я согласен со всем кроме слова Client, в моём понимании это не Client, а, например, ServerException и его наследники или что-то в этом роде. 
Исключение это по факту специальный тип возвращаемого значения. Логика именования по идее такая же, как и возвращаемых ДТО-объектов. Например, в проекте уже есть базовый класс для ответов, и если допустить именование по аналогии, то должно быть скорее BaseResponse/BaseException, чем ClientResponse/ClientException. 
Если посмотреть на реализации в самом dotnet, то исключения либо явно обозначают источник ошибки, например DivideByZeroException, либо обще, но также источник OverflowException, например, но не то, откуда запрос получен, и не того кто будет обрабатывать ответ. Не редко в проектах появляются какие-то внутренние планировщики, которые могут что-то вызывать и ловить исключения, и в таком контексте также не очень понятно кто тут клиент, и про какой клиент вообще речь.

2023-06-30 06:08 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/LoginBizRules/LoginBizRule.cs
> +        await _context.SaveChangesAsync(cancellationToken);
Согласен, на данный момент даже с избытком.

2023-06-30 06:12 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Shared/Exceptions/ClientException.cs
> +    public ClientException() : base() { }
Изначально замечание неверно понял. Думал, что ты о том, что нужно будет обрабатывать ошибку, пришедшую от другого сервиса. А не о том, что мой код вызовет другой сервис.

Про нейминг. Да, соглашусь, что эксепшн одним своим существованием уже должен говорить, что пошло не так. Условно, для ошибок валидации (при пагинации брать минус первую страницу, например) логично будет кидать аля ValidationException. И имхо его стоит делать наследником ClientException. Чтобы глобальная мидлварь ловила лишь один тип исключений.

Чтобы защититься от того, что будет создан пустой непонятный ClientException, его можно сделать абстрактным. Не уверен, что это необходимо

2023-06-30 06:35 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
Имел ввиду не await. Касательно await я как раз полностью согласен. 
Я о том, что меняет здесь ValueTask по сравнению с обычным Task. В такого рода коде повсеместно используется обычный Task, практически во всех сторонних библиотеках, библиотечных методах dotnet и т.п. Существует множество методов расширений для обычного Task, которые для ValueTask в очень редком случае можно будет применить. Т.е. вижу потенциальные ограничения, возможно где-то даже проблемы, по сравнению с обычным Task, но не вижу преимуществ.

2023-06-30 09:50 UTC, adcy approved these changes

2023-06-30 12:24 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Bll/DeviceBizRules/DeviceBizRule.cs
> +    public async ValueTask<IReadOnlyList<DeviceInfo>> GetAll(Pagination pagination, CancellationToken cancellationToken)
Исправлено

2023-06-30 12:26 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/ExceptionMiddleware.cs
> +        catch (ClientException ex)
Исправлено

2023-07-03 05:31 UTC, merged