Dapper and postgres
IAmAnatolyBelanov/InfotecsTestPeriodTask pull request #13
Opened 2023-07-11 11:27 UTC by IAmAnatolyBelanov

2023-07-11 11:56 UTC, SergerGood requested changes

2023-07-11 11:56 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/PgDeviceRepository.cs
> +    ""{nameof(DeviceInfo.OperationSystemType)}"" = @{nameof(parameters.OperationSystemType)},
Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;

2023-07-11 12:24 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/PgDeviceRepository.cs
> +    ""{nameof(DeviceInfo.OperationSystemType)}"" = @{nameof(parameters.OperationSystemType)},
Исправлено

2023-07-12 06:27 UTC, SergerGood requested changes

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Program.cs
> +            Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
Тут хотелось бы увидеть уже группировку логики по методам

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IPgDeviceRepository.cs
> +public interface IPgDeviceRepository
Мне кажется интерфейс не должен говорить о способе реализации. Он описывает контракт, а вот уже его реализация может быть например для постгреса или mssql или в памяти. Тоже касается IPgSession

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IPgDeviceRepository.cs
> +/// Репозиторий для работы с DeviceInfo в БД PostgreSQL.
В комментарии лучше не указывать в виде текста имя классов, Это чревато-то тем, что можно забыть при рефакторинге/переименовании. Лучше писать явно описание сущности, например, репозиторий для работы с устройствами, либо делать ссылку на класс ввиде <see cref=

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/SessionFactory.cs
> +    public IPgSession CreateForPostgres(bool beginTransaction = false)
и вот тут кажется было бы логичнее иметь PgSessionFactory, а метод Create

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/PgSession.cs
> +public class PgSession : IPgSession
Не кажется, что сессия у тебя превращается в один большой репозиторий, т.е. новые методы, которые будут нужны, автоматом появится здесь и будут доступны для всех

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/PgSession.cs
> +            _transaction.Dispose();
кажется незакомиченные транзакции должны быть заролбечены

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Domain/DeviceServices/DeviceService.cs
> +            var statistics = new DeviceStatistics
вот тут похоже на работу для мапстера

2023-07-12 06:27 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/PgDeviceRepository.cs
> +MERGE INTO {DbName} AS TARGET
мержем не пользовался, но как минимум конструкция https://postgrespro.ru/docs/postgrespro/9.6/sql-
INSERT INTO 
    ON CONFLICT DO UPDATE SET
выглядит более понятие, без всяких USING и MATCHED
Но может я не прав и просто не знаю в чем отличие)

2023-07-12 06:40 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IPgDeviceRepository.cs
> +public interface IPgDeviceRepository
Зависит от проекта. Полагаю, здесь проект большим не будет и замечание оправданное. Я же так сделал скорее по привычке. У нас была необходимость в одном сервисе работать сразу с несколькими БД, некоторые из которых отличались в том числе самим типом (mssql/postgres). И нам было важно передавать в репозиторий нужную сессию. Поэтому для каждой бд мы заводили свою - чтоб не ошибиться. И свой интерфейс тоже - всё с той же целью.

Имхо делать же интерфейс общим, а репозиторий частным не очень хорошая идея. Синтаксически всё будет ок, а в рантайме выяснится, что репозиторий смотрит не туда. Для текущего проекта предпочту просто выпилить упоминание Pg из названий вместо заведения общих интерфейсов и частных реализаций.

2023-07-12 06:44 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/PgSession.cs
> +public class PgSession : IPgSession
Немного сам вопрос не понял

2023-07-12 06:48 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Domain/DeviceServices/DeviceService.cs
> +            var statistics = new DeviceStatistics
Возможно... В текущей реализации статистика довольно (какое бы помягче слово подобрать) бесполезна. Всю эту информацию (и даже больше) можно получить, просто запросив информацию о конкретном девайсе (правда в апи такого метода нет). Но если немного концептуально на этот вопрос смотреть - статистика должна собираться на основе нескольких данных, за какой-нибудь период и тд. В таком случае DeviceStatistics - это уже не просто кастрированная dto над DeviceInfo, а отдельная сущность. Поэтому я как-то не очень согласен с применением маппера здесь

2023-07-12 06:51 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/PgDeviceRepository.cs
> +MERGE INTO {DbName} AS TARGET
А, мерж добавился только в 15 версии постгреса. Мне мержить приходилось только в mssql, я по аналогии и для пг сделал. Оказывается, да - исторически вернее будет использовать on conflict. Спасибо - поправлю

2023-07-12 07:14 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IPgDeviceRepository.cs
> +public interface IPgDeviceRepository
ок, давай лучше выпилим упоминание постгреса

2023-07-12 07:14 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/PgSession.cs
> +public class PgSession : IPgSession
договорились пока так оставить

2023-07-12 07:58 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/PgSession.cs
> +            _transaction.Dispose();
https://www.npgsql.org/doc/api/Npgsql.NpgsqlTransaction.html#Npgsql_NpgsqlTransaction_Dispose_System_Boolean_
Disposes the transaction, rolling it back if it is still pending.

Я сначала хотел для очевидности того, что роллбак был, всё же прописать эти строки. Но тут выяснилось, что если транзакция закоммичена, то голый роллбак вызовет исключение. Нужно ещё проверять, закомиччены ли транзакции. Либо try-catch'ами обвешиваться. И то, и другое я бы предпочёл не делать. NpgSql хорошо справляется со своей работой и ролбакает транзакции самостоятельно

2023-07-12 08:06 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/PgSession.cs
> +            _transaction.Dispose();
кажется раньше такого не было, ну ок

2023-07-12 08:13 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Program.cs
> +            Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
Есть

2023-07-12 08:13 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IPgDeviceRepository.cs
> +public interface IPgDeviceRepository
Есть

2023-07-12 08:14 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IPgDeviceRepository.cs
> +/// Репозиторий для работы с DeviceInfo в БД PostgreSQL.
Исправлено. Зная меня, такая проблема могла возникнуть ещё где-то. Не пытался отыскать

2023-07-12 08:14 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Sessions/SessionFactory.cs
> +    public IPgSession CreateForPostgres(bool beginTransaction = false)
есть

2023-07-12 08:14 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/PgDeviceRepository.cs
> +MERGE INTO {DbName} AS TARGET
Есть

2023-07-12 08:31 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Program.cs
> +            Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
ну вобще с учетом всех текущих библиотек и политик самого майкрософт используют классы расширения
https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Basket/Basket.API/Program.cs

2023-07-12 08:31 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IPgDeviceRepository.cs
> +/// Репозиторий для работы с DeviceInfo в БД PostgreSQL.
зная меня, я не пойду проверять везде)

2023-07-12 08:36 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Program.cs
> +            Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
Есть. Хотя для контроллеров оставил как есть. Потому что для них не очень хочется создавать отдельный класс, чтобы сделать методы расширения. Если всё же правильнее вынести в отдельный класс - ок

2023-07-12 08:47 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Program.cs
> +            Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
вполне себе создают) https://github.com/dotnet-architecture/eShopOnContainers/blob/dev/src/Services/Catalog/Catalog.API/Extensions/Extensions.cs

2023-07-12 09:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Program.cs
> +            Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
Есть

2023-07-12 09:09 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Program.cs
> +            Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
на будущее регистрации бизнес сервисов AddSingleton тоже вполне себе можно выносить или группировать логически

2023-07-12 09:09 UTC, SergerGood approved these changes

2023-07-12 09:10 UTC, merged