Device statistics frontend
IAmAnatolyBelanov/InfotecsTestPeriodTask pull request #2
Opened 2023-06-30 07:51 UTC by IAmAnatolyBelanov

2023-06-30 10:42 UTC, SergerGood requested changes

2023-06-30 10:42 UTC, SergerGood commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
https://learn.microsoft.com/ru-ru/azure/architecture/best-practices/api-design
Тут явно не говорится про регистр. Но все же я не встречал чтобы писали в верхнем регистре. Плюс у тебя апи метод должен быть devices если следовать статье

2023-06-30 10:42 UTC, SergerGood commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    this.http.post<any>(url, requestBody).subscribe(response => {
Давай попробуем сразу в парадигсе ангуляра через сервис https://angular.io/tutorial/first-app/first-app-lesson-09

2023-06-30 10:42 UTC, SergerGood commented on Frontend/src/app/devices-table/devices-table.component.ts
> +  selector: 'app-table',
Копипаст остался

2023-06-30 10:43 UTC, SergerGood commented
Вмдимо начальное состояние проектов ушло раньше. Попробуй сразу вместо чистого css настроить Less. В задании этого нет, но что бы сразу попробовать то что у нас на проектах используется

2023-06-30 13:07 UTC, IAmAnatolyBelanov commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Исправлено

2023-06-30 13:07 UTC, IAmAnatolyBelanov commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    this.http.post<any>(url, requestBody).subscribe(response => {
Исправлено

2023-06-30 13:08 UTC, IAmAnatolyBelanov commented on Frontend/src/app/devices-table/devices-table.component.ts
> +  selector: 'app-table',
Исправлено

2023-06-30 13:50 UTC, SergerGood commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Так все же зачем getall? У нас ресурс устройства пр работе с ним получается запрос для работы с коллекцией /devices и все

2023-06-30 13:52 UTC, SergerGood requested changes

2023-06-30 13:52 UTC, SergerGood commented on Frontend/src/app/device.service.ts
> +      .pipe(map(response => response.data));
Вот ты dtoшку ввёл. А почему сразу е не возвращать. Вместо any Devixe[]

2023-06-30 14:49 UTC, IAmAnatolyBelanov commented on Frontend/src/app/device.service.ts
> +      .pipe(map(response => response.data));
Исправлено. Введён BaseResponse

2023-06-30 14:57 UTC, IAmAnatolyBelanov commented
Less добавлен. С пустыми css он довольно хорошо справился

2023-06-30 15:09 UTC, IAmAnatolyBelanov commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Немного не понял. У нас принят чистый rest? С использованием Только Get/Post/Put/Delete/Patch? И для понимания того, что делает апиха, нужно смотреть не столько на её название, сколько на http метод? Ну, как бы, ок - мне просто привычнее другое, когда на одном контроллере может висеть сколько угодно методов, все Post (максимум иногда Get), и назначение различается именно семантикой метода, а не семантикой http метода.

Почему мы вообще такой формат выбирали: мы rest ломали чуть ли не с начала проекта (ещё до моего прихода, но я всё же согласен с этим подходом). Например, для получения списка постов (с прошлой работы пример) мы должны передать данные фильтрации. Этих данных может быть много, и они могут иметь вложенность. Типа

{"filter":{..., "author": {"sex":"male", "minSubscribersCount":1000}, "minViewsCount":1000, ...}}

Укладывать такое в get не удобно. Поэтому делать контроллер Post и в нём держать методы, различные только по http методу мы не стали.

2023-07-03 08:11 UTC, SergerGood commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Это просто стандарты общеприянтые, для удобство понимания и разговора на общем языке. Твоим апи могут пользоваться разные клиенты, на то оно и апи. Да в гет не запихнешь все и мы тоже подменяем методы на пост. И у нас также контроллеры пол сущность с разным количеством методов. Но просто твоё getall само собой подразумевает обычный get или post на ресурс контроллера. В статье об это тоже есть. И вот например примеры апи гитхаб. https://docs.github.com/ru/rest/search/search?apiVersion=2022-11-28#search-code или https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#list-users

2023-07-03 08:14 UTC, SergerGood commented
> Less добавлен. С пустыми css он довольно хорошо справился

:) главное перестроил проект. Сейчас это проще сдедать

2023-07-04 20:42 UTC, IAmAnatolyBelanov commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Исправлено

2023-07-06 13:54 UTC, SergerGood commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Я все таки не успокоюсь) ты видимо не хочешь прочитать статью полностью) там говорится про ресурсы и во множественном ключе. Даже паттерн описан collection/item/collection. Тут кстати можно заюзать атрибут Route, чтобы ввести понятие на весь контроллер 
например https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-7.0#attribute-routing-for-rest-apis

2023-07-06 19:35 UTC, IAmAnatolyBelanov commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Исправлено. По факту, всё ещё не до конца следует статье. Как пример, нейминг пагинации (да, я пожалел, что её добавил=) ), то, что пагинация начинается с первой страницы, а не с нулевого индекса. Здесь больше конфликт привычного и непривычного. Если в команде заведены правила, согласно которым мы следуем этим рекомендациям майкрософт - ок - переименую и пагинацию, начну её с первой страницы, всё такое. Нет - я не понимаю, где будет граница того, чему мы следуем, чему нет. А так как проект пишется мной с нуля, а не копиркой уже существующих проектов компании, то такие вещи будут изучаться поштучно, натыкаясь на грабли

2023-07-07 03:59 UTC, SergerGood commented on Frontend/src/app/devices-table/devices-table.component.ts
> +    const url = 'http://localhost:44500/Device/GetAll';
Так это не только майкрософт. Я тебе и пример с гитхаб скидывал. Можешь поискать на эту тему много всего. Сто процентного единообразия ты не найдёшь, но есть базовые вещи которых все придерживаются. Как я уже говорил это стандарт разговора на одном понятном для всех языке. Пути это самое начало, входная точка. К ней я придирался)

2023-07-07 03:59 UTC, SergerGood approved these changes

2023-07-07 05:59 UTC, merged