Events and tests
IAmAnatolyBelanov/InfotecsTestPeriodTask pull request #23
Opened 2023-07-14 11:15 UTC by IAmAnatolyBelanov

2023-07-14 11:18 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +public class AddEvents : Migration
Поздно спрашиваю, но всё же. У нас нет какого-нибудь стандарта по неймингу миграций? Например, чтобы те начинались всегда с префикса M{datetime}? Чтобы в папке всегда лежали отсортированные

2023-07-14 13:11 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +public class AddEvents : Migration
Мы так делаем 

```
[Migration(2)]
public class AddEvents
```

имя файла 2_AddEvents.cs

2023-07-14 13:32 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +public class AddEvents : Migration
При этом миграции просто +1 номера имеют, или также по датам?

2023-07-14 14:09 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +public class AddEvents : Migration
+1, пока это все сценарии покрывает

2023-07-17 08:23 UTC, SergerGood requested changes

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    public async Task<BaseResponse<DeviceInfoDto>> GetDevice(Guid id, CancellationToken cancellationToken)
Тебя кстати не смутило, что термин в требованиях теперь "узел"?

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +        _logger.LogInformation($"Start to get info about device {id}.");
Вопросы по логированию. 
1. На сколько по твоему уместно все входящие запросы логировать на уровне Info.
2. Есть ли смысл логировать информацию по завершению работы метода.

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    /// Добавляет событие в БД.
в контроллере писать что добавление в БД как-то...

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    public async Task<BaseResponse<Guid>> AddEvent(DeviceEventDto deviceEvent, CancellationToken cancellationToken)
А почему только одно событие? По условию вроде бы "приложение connect будет присылать накопившийся **список** событий"

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    [HttpGet("by-device-id")]
кажется такой "говорящий апи" избыточен. Это обычный get для ресурса events, который возварщает коллекцию, а параметры это deviceId

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDto.cs
> +/// Dto класса DeviceEvent.
уже говорил что лучше не использовать raw данные классов

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDtoLight.cs
> +public class DeviceEventDtoLight
мне лично больше нарвится термин simple, но это на мое усмотрение

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/EventCollection.cs
> +public class EventCollection
Ты вроде используешь Dto для контрактов, почему здесь тогда нет?

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDtoLight.cs
> +public class DeviceEventDtoLight
Кажется Dto все таки это постфикс, т.е. в конце должно быть

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +        Delete.Table("events");
не упадет на ForeignKey?

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +            .WithColumn("date").AsDateTimeOffset().NotNullable();
мне привычнее видеть понятие **datetime**, если есть еще и время, а здесь вроде бы есть

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/EventRepository.cs
> +    public async Task InsertEvent(ISession session, DeviceEvent deviceEvent, CancellationToken cancellationToken)
точно не Add?)

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IEventRepository.cs
> +    /// Добавляет событие в БД.
может лучше без терминов БД?  Ну как минимум я могу реализовать интерфейс для работы в памяти

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/DeviceEventLightMapper.g.cs
что-то чем дальше тем больше мне это не нравится, слишком много "мусора" для маппера

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +            Id = Guid.Parse("00000000-0000-0000-0001-000000000001"),
а чего не Guid.NewGuid?

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    public async Task RegisterDevice_Correct_Success()
А ты  c AutoFixture не работал случайно?

2023-07-17 08:23 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    }
А еще не слышал про FluentAssertions?

2023-07-17 08:26 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    public async Task<BaseResponse<DeviceInfoDto>> GetDevice(Guid id, CancellationToken cancellationToken)
Смутило. Так сказать, более узнаваемое название в пределах инфотекса. Но тк. текущее задание только на добавление фунционала, но не на рефактор/техдолг, то пока не стал заострять на этом внимание

2023-07-17 08:29 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +        _logger.LogInformation($"Start to get info about device {id}.");
1. Уместно. Логи мы обычно смотрим, когда всё пошло плохо. И в этом случае хотелось бы видеть, когда что началось. При этом это не warn. Может логичнее дебуг. Но имхо иметь инфу о начале запроса может оказаться полезным

2. Смысл есть. И Enrich.FromLogContext() серилога эту задачу покрывает

2023-07-17 08:32 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    public async Task<BaseResponse<Guid>> AddEvent(DeviceEventDto deviceEvent, CancellationToken cancellationToken)
Вообще, логично. Не подумал о том, что можно список ивентов слать. А так как смотрел в основном на пункт "добавить функционал", то и привязался к фразе "Сохранять события" - без указания того, поштучно, или батчем. Исправлю

2023-07-17 08:33 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    [HttpGet("by-device-id")]
Не соглашусь. Обычный гет, у которого в аргументах id - интуитивно должен вернуть запись по этому айдишнику. Тут же гет с аргументом в виде айдишника - от него не ожидаешь того, что айдишник этот девайса, и что возвращён будет целый список

2023-07-17 08:35 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDto.cs
> +/// Dto класса DeviceEvent.
Говорил. И тут я бы предпочёл пренебречь этим правилом. У проекта Contracts нет зависимости от Dal (насколько помню, именно там моделька лежит). И имхо не должно появиться.

2023-07-17 08:36 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +        Delete.Table("events");
Удалял вручную - не падало. Но мб мне sql студия сама каскадное удаление прописала - проверю на всякий

2023-07-17 08:37 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +            .WithColumn("date").AsDateTimeOffset().NotNullable();
Пытался быть ближе к тз. Исправлю

2023-07-17 08:37 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/EventRepository.cs
> +    public async Task InsertEvent(ISession session, DeviceEvent deviceEvent, CancellationToken cancellationToken)
Имхо с точки зрения репозитория - insert. С точки зрения Domain'а уже может быть Add

2023-07-17 08:41 UTC, SergerGood requested changes

2023-07-17 08:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +        Assert.Null(result.Data);
Смущает такая постановка валидации ответа контроллера. Выглядит как ничего не произошло. Может тогда еще и статус стоит проверять?

2023-07-17 08:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    public async Task GetDevice_Correct_Success()
для второго пункта в имени кажется нужно указать условие. Вот если так, то термин что они просто корректные звучит уж больно асбтрактно. Мне кажется более корректно указать что мы делаем выборку по существующему устроуству

2023-07-17 08:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        var result = await deviceService.GetStatistics(id, CancellationToken.None);
кстати вместо CancellationToken.None можно писать default

2023-07-17 08:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        var deviceService = new DeviceService(_sessionFactory.Object, deviceRepository.Object);
Может моки сервиса и репозитория тоже вынесли в общую инициализацию?

2023-07-17 08:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +    /// Конструктор класса <see cref="DeviceServiceTests"/>.
вот в тестах кстати я пишу, что это уже не конструктор, а инициализация

2023-07-17 08:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        deviceRepository.Setup(x => x.GetDevice(It.IsAny<ISession>(), It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
все-таки честнее в тесте сетапить именно на тот Id, который будет вызываться. Как и когда проверяем что был вызван метод мока

2023-07-17 08:41 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +            Events = events.Select(_deviceEventLightMapper.MapToDto).ToArray(),
все таки не понял в чем смысл выделения упрощенной дто по евент и группировка по девайсу

2023-07-17 08:42 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    public async Task<BaseResponse<DeviceInfoDto>> GetDevice(Guid id, CancellationToken cancellationToken)
ну вот да, обучение замутнеет сознание)
ну так все же, получается по бизнесу произошла подмена термина. что в этом случае делать?

2023-07-17 08:45 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +            Id = Guid.Parse("00000000-0000-0000-0001-000000000001"),
В тестах предпочитаю максимально контролировать вставляемые/добавляемые данные. Уже плохо помню, откуда привычка пошла - скорее всего желание получать на абсолютно каждом прогоне максимально схожие результаты. И потом при ошибках чтоб была возможность найти по гуиднику, что именно не там где надо оказалось (условно, при ручном маппинге не тот айдишник скопировал - чтобы по этому самому айдишнику можно было найти, что не так скопировалось)

2023-07-17 08:45 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    public async Task RegisterDevice_Correct_Success()
Нет

2023-07-17 08:46 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    [HttpGet("by-device-id")]
возвращаемся к rest api
https://learn.microsoft.com/en-us/azure/architecture/best-practices/api-design

<html>
<body>
<!--StartFragment-->

Resource | POST | GET | PUT | DELETE
-- | -- | -- | -- | --
/customers | Create a new customer | **Retrieve all customers** | Bulk update of customers | Remove all customers
/customers/1 | Error | **Retrieve the details for customer 1** | Update the details of customer 1 if it exists | Remove customer 1
/customers/1/orders | Create a new order for customer 1 | Retrieve all orders for customer 1 | Bulk update of orders for customer 1 | Remove all orders for customer 1

<!--EndFragment-->
</body>
</html>

просто get это список, а get/id это по конкретному ресурсу

2023-07-17 08:47 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDto.cs
> +/// Dto класса DeviceEvent.
тогда лучше использовать бизнес термины

2023-07-17 08:48 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    }
Нет. Хотя выглядит приятно

2023-07-17 08:49 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/EventRepository.cs
> +    public async Task InsertEvent(ISession session, DeviceEvent deviceEvent, CancellationToken cancellationToken)
возможно, но кажется общая терминология упрощает жизнь, т.к. понятие добавление везде звучит одинаков. Например если ищешь все методы/логику с добавлением сущност что-то типа Add*Device*

2023-07-17 08:52 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    }
могу посоветовать использовать хотя бы один его метод [BeEquivalentTo](https://fluentassertions.com/objectgraphs/)
Код сильно упростится для таких сравнений, у стандартного так не будет работать

2023-07-17 08:52 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    public async Task RegisterDevice_Correct_Success()
тоже рекомендую посмотреть когда будут просадки по времени с ревю, можно ишью завести

2023-07-17 08:53 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        var deviceService = new DeviceService(_sessionFactory.Object, deviceRepository.Object);
Имхо не стоит. Можно случайно расшарить между тестами ненужные данные. Ну, вернее, указать в инициализации репозиторий, ему в сетап закинуть данные, нужные для теста А, тем самым сломав тест Б. Если память не подводит, xUnit на каждый тест запускает новый инстанс класса тестов, и наверно в пределах одного теста если объявлять все контекстно-зависимые сетапы, то наверно всё будет норм. Но привычка контекстно зависимые штуки держать полностью в пределах тестового метода

2023-07-17 08:54 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +            Events = events.Select(_deviceEventLightMapper.MapToDto).ToArray(),
Такой формат был в тз... Я лентяй - я бы просто массив ивентов выплюнул бы. Забив на то, что в каждом иветне повторяется поле DeviceId

2023-07-17 08:58 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    public async Task<BaseResponse<DeviceInfoDto>> GetDevice(Guid id, CancellationToken cancellationToken)
Переговорить с бизнесом. Если бизнес всё же настаивает на подмене понятий - фронтенду придётся менять названия на UI. В идеале, вообще только в файлах локализации. Но ходить и переименовывать классы или, ещё хуже, поля и методы я бы не стал. Обратная совместимость сразу пропадает, плюс чёрт его знает, где при ручном ренейме забыл что-то переименовать, а при массовом где переименовал лишнее

2023-07-17 08:59 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +            Id = Guid.Parse("00000000-0000-0000-0001-000000000001"),
ну искать тесты мне кажется можно и по имени теста + если что-то не так то это надо понять в превую очередь по ошибкам теста
А вот при каждом прогоне абслютно одинаковые данные это тоже спорно, по факту так тест может завязаться на входные данные и скрывать проблему. Вот как раз эту проблему решает AutoFixture

2023-07-17 09:02 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    [HttpGet("by-device-id")]
Не увидел противоречий с моим комментом. /customers/1 - ты ожидаешь получить первого кастомера (как и /events/{guid}). А уже чтобы соответствовать ресту скорее придётся делать роутинг аля /customers/1/orders (devices/{guid}/events)

То есть если был намёк на то, что метод находится не в своём контроллере - нуууу.... вновь побухчу и скажу, что раз в команде так принято - ок. Мне же events/get-by-device нравится больше

Если намёк был на что-то ещё - я не понял намёк

2023-07-17 09:03 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    public async Task<BaseResponse<DeviceInfoDto>> GetDevice(Guid id, CancellationToken cancellationToken)
просто мы тогда упираемся в то, что бизнес будет говорить с нами на другом языке и придется в уме всегда держать соответствие понятий

2023-07-17 09:04 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        var deviceService = new DeviceService(_sessionFactory.Object, deviceRepository.Object);
ок, принято

2023-07-17 09:05 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +            Events = events.Select(_deviceEventLightMapper.MapToDto).ToArray(),
да, кстати по тз так, ну ок)

2023-07-17 09:07 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    public async Task<BaseResponse<DeviceInfoDto>> GetDevice(Guid id, CancellationToken cancellationToken)
Да. Мы так и жили, в общем-то, на прошлом месте. Ещё до меня пытались в версионность api - получилось плохо. Решили либо менять методы постепенно (я был очень против - вместо того, что у нас проблема "бизнес говорит узел, а мы девайс" у нас стала проблема "бизнес говорит узел, а мы ИНОГДА девайс, ИНОГДА узел"), не ломая старый функционал. А чаще всё же использовали старый нейминг.

Так со стороны описал ситуацию - выглядит плохо. А лучше я пока не придумал. Только версионность. Но это довольно тяжёлая штука имхо.

2023-07-17 09:55 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    public async Task<BaseResponse<DeviceInfoDto>> GetDevice(Guid id, CancellationToken cancellationToken)
ну чаще всего так и живут, но более отчаянные ради лучшей жизни переименовывают в коде все

2023-07-17 12:25 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    public async Task<BaseResponse<Guid>> AddEvent(DeviceEventDto deviceEvent, CancellationToken cancellationToken)
Добавил ещё один метод для массового внесения ивентов

2023-07-17 13:04 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +        Delete.Table("events");
Не, не падает. Связанные данные в таблицах были.

2023-07-17 13:04 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    /// Добавляет событие в БД.
Исправлено

2023-07-17 13:04 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDto.cs
> +/// Dto класса DeviceEvent.
Исправлено

2023-07-17 13:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDtoLight.cs
> +public class DeviceEventDtoLight
В тфс, помню, есть прекрасный вариант - не Resolve помечать, а won't fix. Но чёт в гитхабе найти не могу

2023-07-17 13:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/EventCollection.cs
> +public class EventCollection
Исправлено

2023-07-17 13:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Contracts/DeviceEvents/DeviceEventDtoLight.cs
> +public class DeviceEventDtoLight
Исправлено

2023-07-17 13:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +            .WithColumn("date").AsDateTimeOffset().NotNullable();
Исправлено

2023-07-17 13:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/EventRepository.cs
> +    public async Task InsertEvent(ISession session, DeviceEvent deviceEvent, CancellationToken cancellationToken)
Исправлено

2023-07-17 13:05 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Repositories/IEventRepository.cs
> +    /// Добавляет событие в БД.
Исправлено

2023-07-17 13:14 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +        Assert.Null(result.Data);
Исправлено. В приватном методе, ещё до возвращения baseResponse добавлена проверка

2023-07-17 13:18 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +    /// Конструктор класса <see cref="DeviceServiceTests"/>.
Ну, это вроде нейминг MSTest (TestInitialize). Тут это же вроде прям честный конструктор

2023-07-17 13:20 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        deviceRepository.Setup(x => x.GetDevice(It.IsAny<ISession>(), It.IsAny<Guid>(), It.IsAny<CancellationToken>()))
Исправлено

2023-07-17 13:25 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        var result = await deviceService.GetStatistics(id, CancellationToken.None);
Можно. Но тут становится неочевидно, что передаётся. Сравни передачи null. Ты либо приписываешь имя аргумента (`cancellationToken: default`), либо миришься с тем что понимать аргумент можно будет лишь взглянув на объявление метода (ну или подсказками студии), либо пишешь аля `default(CancellationToken)`. Все перечисленные варианты мне нравятся меньше, чем CancellationToken.None

В очередной раз подмечу - если команда привыкла всегда писать default - ок, исправлю - это не тот вопрос, ради которого я готов что-то отстаивать, спорить и так далее - удобство целого коллектива тут важнее

2023-07-17 13:26 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    public async Task<BaseResponse<Guid>> AddEvent(DeviceEventDto deviceEvent, CancellationToken cancellationToken)
А почему на COPY, в даппер вроде можно передать коллекцию и он вставит, правда не балком но вставит все по одной

2023-07-17 13:28 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +    /// Конструктор класса <see cref="DeviceServiceTests"/>.
да, но xunit использует его как инициализатор, поэтому мне такой нейминг нарвится

2023-07-17 13:28 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +    /// Конструктор класса <see cref="DeviceServiceTests"/>.
ну ладно не принципиально. Просто комменатрии все таки несут суть

2023-07-17 13:28 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    public async Task GetDevice_Correct_Success()
Исправлено. В рамках остальных тестов тоже

2023-07-17 13:29 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    public async Task<BaseResponse<Guid>> AddEvent(DeviceEventDto deviceEvent, CancellationToken cancellationToken)
Собственно потому что по одной вставит. Булка мне нравится больше

2023-07-17 13:30 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.UnitTests/Devices/DeviceServiceTests.cs
> +        var result = await deviceService.GetStatistics(id, CancellationToken.None);
согласен с тобой, что скрывает реализацию. Просто для асинхронных вызовов, за частую последний аргумент это токен отмены, поэтому лично для меня допустимо. 
На счет принято в команде, тут нет жестокого правила

2023-07-17 13:32 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +        Assert.Null(result.Data);
а не правильнее делать ее на ассерте?

2023-07-17 13:42 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +        Assert.Null(result.Data);
Согласен. Забыл, что я в тестовом классе. Исправлено

2023-07-17 14:01 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +        Assert.Null(result.Data);
подожди. Метод, который создает в тесте что-то и тут же ассертит... ну для начала метод об этом не говорит, а во-вторых мне кажется, что это дело не метода по созданию устройства проверять, которые используется всеми тестами, а ответственность самого теста по созданию

2023-07-17 14:02 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +            Id = Guid.Parse("00000000-0000-0000-0001-000000000001"),
можно накинуть ишью если что

2023-07-17 14:03 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    [HttpGet("by-device-id")]
По-хорошему с точки зрения rest должно быть devices/{guid}/events и метод в контроллере устройств.
Либо как компромиссный вариант, если мы допускаем, что events у нас могут быть когда запрошены и без привязки к одному устройству, можно использовать query param, например, /events?deviceId={guid}

2023-07-17 14:03 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    [HttpGet("by-device-id")]
ну ты правильно понял evices/{guid}/events логичнее всего. Но давай компромис) 
get-by-device, чего точно не делают в апи методах, так это не описывают rest-действие, давай остановимся на by-device?

2023-07-17 14:04 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +public class AddEvents : Migration
планируешь или нет, ишью или закрываем?

2023-07-17 14:36 UTC, adcy requested changes

2023-07-17 14:36 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +            Events = events.Select(_deviceEventLightMapper.MapToDto).ToArray(),
`.ToArray()`
Лучше не использовать ToArray, там где не требуется явно именно массив.
Потому что ToArray это ToList() + ToArray()  в общем случае, т.е. потребление памяти чуть мене чем в два раза больше у ToArray().

2023-07-17 14:36 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Shared/GuidProviders/GuidProvider.cs
> +public class GuidProvider : IGuidProvider
А для чего это может понадобиться? 
Эдак ведь можно дойти до IntProvider, NullProvider и т.д. 😉

2023-07-17 14:36 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    [HttpGet("{id?}")]
А почему id? с вопросиком? Это значит что его может не быть в запросе, но метод будет вызван все равно?

2023-07-17 14:36 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    public async Task<BaseResponse<EventCollectionDto>> GetEventsByDevice(Guid deviceId, CancellationToken cancellationToken)
Кстати, если не указан атрибут перед параметром, где asp net его ожидает, где угодно?

2023-07-17 14:36 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Domain/DeviceEventServices/DeviceEventService.cs
> +            deviceEvent.Id = _guidProvider.NewGuid();
А почему это тут происходит? Вот я приду на проект через 5 лет, вызову этот сервис и будут недоумевать, почему я идентификатор в коде задаю один, а в базу попадает другой.

2023-07-17 14:36 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/DeviceEventLightMapper.g.cs
> +            if (p2 == null)
Это автогенерированный код?

2023-07-17 14:43 UTC, adcy requested changes

2023-07-17 14:43 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +[Route("events")]
Как правило API пути стараются под один префикс какой-то поместить, например /api/events. Это позволяет избежать коллизий по путям, когда у нас и фронт и API на одном домене.

2023-07-17 14:58 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +            Events = events.Select(_deviceEventLightMapper.MapToDto).ToArray(),
![image](https://github.com/IAmAnatolyBelanov/TestPeriodTask/assets/98072721/fbae2009-e806-4ba6-8afa-20f54fb1b43b)
![image](https://github.com/IAmAnatolyBelanov/TestPeriodTask/assets/98072721/3a81316a-c80b-4655-9c7c-3b7a133b22bf)

Не согласен. ToArray вполне самостоятелен. То, что ты говоришь, справедливо для EF (не помню, только для него, или для всего IQueryable) - там да, если под капот заглянуть, ToArray дёргает ToList

2023-07-17 15:01 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Dal/Migrations/AddEvents.cs
> +public class AddEvents : Migration
Не планирую. Ишью можно

2023-07-17 15:01 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Domain/DeviceEventServices/DeviceEventService.cs
> +            deviceEvent.Id = _guidProvider.NewGuid();
Ты не задаёшь Id для ивента. По контракту в тз ивент содержит только deviceId, name и date (последнее переименовано в dateTime) - собственного id у него нет. Иными словами, этот id никогда не светится наружу

2023-07-17 15:02 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/DeviceEventLightMapper.g.cs
> +            if (p2 == null)
Да

2023-07-17 15:29 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +            Events = events.Select(_deviceEventLightMapper.MapToDto).ToArray(),
Только при повторном просмотре увидел, что забыл убрать приватный list. Вот обновлённый бенч:

![image](https://github.com/IAmAnatolyBelanov/TestPeriodTask/assets/98072721/24a07bbd-65af-439e-a976-a9d41727b57f)

2023-07-17 15:31 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Shared/GuidProviders/GuidProvider.cs
> +public class GuidProvider : IGuidProvider
Для тестов. Это сродни IClock - чтобы не завязываться на Guid.NewGuid() (в случае с IClock - на DateTimeOffset.UtcNow). Чтобы во время тестирования можно было моками контролировать результаты

2023-07-17 15:31 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    public async Task<BaseResponse<EventCollectionDto>> GetEventsByDevice(Guid deviceId, CancellationToken cancellationToken)
Да. Для гета можно только в урле

2023-07-18 06:35 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +    }
https://github.com/IAmAnatolyBelanov/TestPeriodTask/issues/26

2023-07-18 07:25 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +        Assert.Null(result.Data);
Сейчас прокину в качестве ответа метода не только BaseRespons<>, но http'шный респонс. А в дальнейших апи методах, которые ничего не возвращают, буду просто строку "Ok" возвращать. Чтобы проверки на успешность проще были

2023-07-18 07:34 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    [HttpGet("{id?}")]
Особо не задумавшись скопировал откуда-то. Проверил - с вопросиком параметр тоже обязателен, без вопросика работает, на msdn ничего похожего нет. Откуда скопировал - для меня пока загадка. Но в любом случае вопросик сотру

2023-07-18 07:52 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +    [HttpGet("by-device-id")]
Компромисс

2023-07-18 07:52 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.IntegrationTests/Devices/DevicesTests.cs
> +        Assert.Null(result.Data);
Есть

2023-07-18 07:52 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/DeviceController.cs
> +    [HttpGet("{id?}")]
Есть

2023-07-18 07:52 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +[Route("events")]
Есть

2023-07-18 10:59 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Domain/DeviceEventServices/DeviceEventService.cs
> +            deviceEvent.Id = _guidProvider.NewGuid();
Ничего не знаю про задание ) 
Я в этот метод передаю сущность с одним Id, а в результате у неё другой Id.

2023-07-18 10:59 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/DeviceEventLightMapper.g.cs
> +            if (p2 == null)
Странно что не добавляется  аннотация `<auto-generated> </auto-generated>` в шапке, без неё анализаторы будут ругаться на этот код.

2023-07-18 10:59 UTC, adcy commented on Backend/Monitoring/Source/Monitoring.Api/Controllers/EventController.cs
> +            Events = events.Select(_deviceEventLightMapper.MapToDto).ToArray(),
Огонь! Молодец, что проверил!
Посмотрел реализацию, сейчас ToArray меньше памяти потребляет. Раньше было наоборот. А по скорости были одинаково, теперь ToArray быстрее, из бенча тоже видно это.

2023-07-18 11:48 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Domain/DeviceEventServices/DeviceEventService.cs
> +            deviceEvent.Id = _guidProvider.NewGuid();
Перенёс логику в контроллер

2023-07-18 12:50 UTC, adcy approved these changes

2023-07-18 14:05 UTC, merged