Events - front
IAmAnatolyBelanov/InfotecsTestPeriodTask pull request #24
Opened 2023-07-14 11:53 UTC by IAmAnatolyBelanov

2023-07-17 14:40 UTC, adcy requested changes

2023-07-17 14:40 UTC, adcy commented on Frontend/src/app/event.service.ts
> +    const url = `http://localhost:44500/events/by-device-id`;
А тут разве обязательно прописывать имя хоста? Относительного пути не будет достаточно?

2023-07-17 14:40 UTC, adcy commented on Frontend/src/app/events-table/events-table.component.ts
> +      this.deviceId = params.get('deviceId')!;
Зачем обманывать анализатор восклицательным знаком )

2023-07-18 08:36 UTC, IAmAnatolyBelanov commented on Frontend/src/app/event.service.ts
> +    const url = `http://localhost:44500/events/by-device-id`;
Недостаточно. Вообще, полагаю, недостаточно из-за порта, но не знаю, как это доказать или опровергнуть

2023-07-18 08:39 UTC, IAmAnatolyBelanov commented on Frontend/src/app/events-table/events-table.component.ts
> +      this.deviceId = params.get('deviceId')!;
А иначе он меня ругает. Говорит, deviceId не поддерживает `string | null`

2023-07-18 11:18 UTC, adcy commented on Frontend/src/app/events-table/events-table.component.ts
> +      this.deviceId = params.get('deviceId')!;
Так надо выше объявить deviceId как nullable: `deviceId?: string;`

2023-07-18 12:05 UTC, IAmAnatolyBelanov commented on Frontend/src/app/events-table/events-table.component.ts
> +      this.deviceId = params.get('deviceId')!;
Дальше меня компилятор ругает при попытке передать нуловую строку в getEventsByDeviceId. Поставил проверку перед тем, как записывать this.DeviceId

2023-07-18 12:48 UTC, adcy commented on Frontend/src/app/events-table/events-table.component.ts
> +      this.deviceId = params.get('deviceId')!;
Так и правильно же ругает, разве нет? Ведь ситуация с пустым идентификатором возможна, и где-то её нужно обработать в конце концов.
Явная и определенная ошибка наверное лучше, чем непредвиденное поведение. Но я бы ожидал, что в случае отсутствия идентификатора будет отрисована либо пустая страница, либо будет, например список устройств, или редирект куда-то.

2023-07-18 13:52 UTC, IAmAnatolyBelanov commented on Frontend/src/app/events-table/events-table.component.ts
> +      this.deviceId = params.get('deviceId')!;
![image](https://github.com/IAmAnatolyBelanov/TestPeriodTask/assets/98072721/773f8ae7-d9c0-46dd-abbd-9d8c89a14df9)


![image](https://github.com/IAmAnatolyBelanov/TestPeriodTask/assets/98072721/672ff931-17e0-4096-ab13-7eba9f43fbd2)

1 - если не ввести айдишник совсем, 2 - если ввести некорректный (синтаксически некорректный. Если просто несуществующий id - визуально то же будет, только никто ругаться при этом не будет)

2023-07-18 15:21 UTC, adcy approved these changes

2023-07-18 15:30 UTC, adcy commented on Frontend/src/app/events-table/events-table.component.ts
> +      this.deviceId = params.get('deviceId')!;
Хорошо. Не всегда так удачно получается. Частенько случается так, что при отсутствующем ID запрос из /device/id/events вырождается в /device//events и попадет не туда, а дальше как повезет. 
Обычно в таких случаях просто пропускают пустые значения из url, т.е. достаточно было бы написать if deviceId) { this.getEvents(deviceId); } было бы понятно и анализатор бы не ругался.

2023-07-19 06:13 UTC, merged