#2 Using seq
IAmAnatolyBelanov/InfotecsTestPeriodTask pull request #7
Opened 2023-07-07 06:22 UTC by IAmAnatolyBelanov

2023-07-07 06:49 UTC, SergerGood requested changes

2023-07-07 06:49 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/LoggerRegister.cs
> +            .WriteTo.Seq("http://localhost:5341")
Коль мы как раз тут и хотим все попробовать и узнать как работает.
Ты ишью как раз заводил на эту тему, правда более масштабное.
Давай сразу вынесем конфигурацию серилога в appsettings.json, чтобы ей можно было управлять.
Заодно задай путь хранения не кастомный а относительный. С учетом того, что все приложения рано или поздно начнут хостится на линуксе, то лучше придерживаться при именовании путей нижнего регистра, т.к. линукс регистрозависим

2023-07-10 07:30 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/LoggerRegister.cs
> +            .WriteTo.Seq("http://localhost:5341")
Сделано. 2 оговорки:

1. Не только пути были вынесены в конфиг.
2. Для локального запуска я всё же оставил абсолютный путь. Проверил с относительным путём, но для локальной работы мне всё же удобнее держать абсолютный путь - у разных разработчиков папка с репозиторием может лежать в очень разных местах, и не всем будет удобно работать через относительные пути.

2023-07-10 07:40 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/LoggerRegister.cs
> +            .WriteTo.Seq("http://localhost:5341")
Хотя чёт я не подумал, что разраб сам на линуксе/маке сидеть может... В этом случае ему абсолютный путь мешать будет...

2023-07-10 08:03 UTC, SergerGood requested changes

2023-07-10 08:03 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/appsettings.Development.json
> +    "FilePath": "C:\\Logs\\Monitoring.Api\\log_.log",
program data

2023-07-10 08:03 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/Logger/LoggerRegister.cs
> +    {
https://github.com/serilog/serilog-aspnetcore

2023-07-10 08:31 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/appsettings.Development.json
> +    "FilePath": "C:\\Logs\\Monitoring.Api\\log_.log",
Исправлено

2023-07-10 08:31 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Api/Infrastructure/Logger/LoggerRegister.cs
> +    {
Исправлено

2023-07-10 08:36 UTC, SergerGood commented
про ProgramData я имел ввиду это %PROGRAMDATA%

2023-07-10 08:37 UTC, SergerGood approved these changes

2023-07-11 05:57 UTC, IAmAnatolyBelanov commented
> про ProgramData я имел ввиду это %PROGRAMDATA%

Исправил

2023-07-11 05:57 UTC, merged