Using mapster
IAmAnatolyBelanov/InfotecsTestPeriodTask pull request #8
Opened 2023-07-07 06:22 UTC by IAmAnatolyBelanov

2023-07-07 06:58 UTC, SergerGood requested changes

2023-07-07 06:58 UTC, SergerGood commented on Backend/Monitoring/.config/dotnet-tools.json
а держать эти конфиги в репозитории для чего? я даже сходу не помню в чем их смысл

2023-07-07 06:58 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/Models/DeviceInfoDto.cs
> +using Infotecs.Monitoring.Dal.Models;
мне почему-то кажется что dto это больше про контракты, а не про модели. Логичнее из видеть либо отдельно от домена, нет?

2023-07-07 06:58 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/IDeviceInfoMapper.cs
> +public interface IDeviceInfoMapper
т.е. получается мы описываем инетрфейс, а на основании его мапстер генерит мапинги? пока выглядит как оверхед... обычно мапстреру достаточно описать поведение только для неидентичного маппинга, т.е. на 1 в 1, и только тех полей которые нужно. Ну т.е. телодвижений куда меньше. Плюс не понятно как кастомизировать как раз такое поведение в этой схеме

2023-07-07 07:00 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/.config/dotnet-tools.json
Это необходимое условие для работы тулзы для автогенерации

2023-07-07 08:49 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/IDeviceInfoMapper.cs
> +public interface IDeviceInfoMapper
>получается мы описываем инетрфейс, а на основании его мапстер генерит мапинги?
Ага.

>телодвижений куда меньше [при обычном маппинге - без автогенерации]
Согласен. Частично. И с генерацией, и без генерации мы должны объявить маппер и прописать правила для маппинга не 1к1. В случае генерации добавляются: команда для, собственно, генерации (можно автоматом на билд повесить, но я не уверен, что билд тогда всегда корректно проходить будет), прокидывание di (сюда же включил написание правил маппинга). Имхо цена приемлемая за возможность предсказывать поведение маппинга - даже при изменении моделей. Но это только моё мнение

>не понятно как кастомизировать как раз такое [не 1 к 1] поведение
В случае чего-то простого достаточно в MapperRegister.Register прописать
```
config.NewConfig<DeviceInfo, DeviceInfoDto>()
            .Map(dst => dst.UserName, src => src.OperationSystemType.ToString() + "-" + src.UserName);
```
И строка 1в1 будет перенесена в маппинг. Есть также игнор
Для более сложной логики есть возможность задать AfterMapping, BeforeMapping. Там некоторые ограничения есть, но суть та же

2023-07-07 09:12 UTC, SergerGood commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/IDeviceInfoMapper.cs
> +public interface IDeviceInfoMapper
Вобщем настаивать на удалении не буду) Даже интересно что в итоге получится, если модель будет меняться и усложняться.
Но тот способ, про который я говорю, на выходе содержит в себе только тот код, который ты в комменте добавил.

2023-07-07 09:14 UTC, SergerGood commented on Backend/Monitoring/.config/dotnet-tools.json
ну вот по мне так это в сторону усложнения и про привязку к инструментам

2023-07-07 09:15 UTC, SergerGood commented on Backend/Monitoring/.config/dotnet-tools.json
закрою коммент, т.к. оставляем и смотрим такой вариант работы с маппером

2023-07-10 06:06 UTC, IAmAnatolyBelanov commented
Там был как-то вопрос про то, как конфигурировать мапстер с его автогеном. Тут проблема одна обнаружилась. Она решаемая, но всё равно неприятная.

https://stackoverflow.com/questions/76646302/mapster-injection

Пока мне на этот вопрос ответить никто не смог. И чувствую, не ответит. В вопросе описал, как можно "сложное" конфигурирование сделать, но сделать криво.

2023-07-10 08:07 UTC, IAmAnatolyBelanov commented on Backend/Monitoring/Source/Monitoring.Domain/Mappers/Models/DeviceInfoDto.cs
> +using Infotecs.Monitoring.Dal.Models;
Исправлено

2023-07-10 08:34 UTC, SergerGood approved these changes

2023-07-11 05:57 UTC, merged